version: '2'
services:
  postgres:
    image: postgres:latest
    container_name: bikerly
    environment:
      POSTGRES_DB: bikerly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data